import {
  Product,
  Category,
  Banner,
  Order,
  Address,
  Notification,
} from '@/types';

export const mockBanners: Banner[] = [
  {
    id: '1',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800',
    title: 'Summer Sale',
    subtitle: 'Up to 70% off',
  },
  {
    id: '2',
    image: 'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800',
    title: 'Fashion Trends',
    subtitle: 'New arrivals',
  },
  {
    id: '3',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
    title: 'Electronics',
    subtitle: 'Best deals',
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Medical & Pharmacy',
    slug: 'medical-and-pharmacy',
    image: 'https://cdn-icons-png.flaticon.com/512/3022/3022567.png',
    subcategories: ['Medicines', 'Ayurveda', 'Health Devices'],
  },
  {
    id: '2',
    name: 'Groceries',
    slug: 'groceries',
    image: 'https://cdn-icons-png.flaticon.com/512/3724/3724788.png',
    subcategories: ['Vegetables', 'Fruits', 'Dairy', 'Beverages', 'Snacks'],
  },
  {
    id: '3',
    name: 'Fashion & Beauty',
    slug: 'fashion-and-beauty',
    image: 'https://cdn-icons-png.flaticon.com/512/3050/3050239.png',
    subcategories: ["Men's Clothing", "Women's Clothing", "Kids' Fashion", 'Shoes', 'Watches', 'Bags & Luggage'],
  },
  {
    id: '4',
    name: 'Devices',
    slug: 'devices',
    image: 'https://cdn-icons-png.flaticon.com/512/644/644458.png',
    subcategories: ['Mobiles', 'Laptops', 'Tablets', 'Smart Watches', 'Headphones'],
  },
  {
    id: '5',
    name: 'Electrical',
    slug: 'electrical',
    image: 'https://cdn-icons-png.flaticon.com/512/3659/3659899.png',
    subcategories: ['Wiring', 'Switches', 'Bulbs'],
  },
  {
    id: '6',
    name: 'Automotive',
    slug: 'automotive',
    image: 'https://cdn-icons-png.flaticon.com/512/296/296216.png',
    subcategories: ['Car Accessories', 'Bike Accessories', 'Spare Parts'],
  },
  {
    id: '7',
    name: 'Sports',
    slug: 'sports',
    image: 'https://cdn-icons-png.flaticon.com/512/857/857455.png',
    subcategories: ['Cricket', 'Football', 'Fitness'],
  },
  {
    id: '8',
    name: 'Home Interior',
    slug: 'home-interior',
    image: 'https://cdn-icons-png.flaticon.com/512/263/263115.png',
    subcategories: ['Decor', 'Furniture', 'Curtains'],
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Parachute Advansed Cocoa Butter Body Lotion',
    description: 'Nourishing body lotion with cocoa butter',
    price: 349,
    originalPrice: 450,
    discount: 22,
    images: [
      'https://m.media-amazon.com/images/I/61N+6Jj-C9L._SL1500_.jpg',
    ],
    category: 'Fashion & Beauty',
    subcategory: 'Skincare',
    rating: 4.5,
    reviewCount: 1234,
    inStock: true,
    brand: 'Parachute',
  },
  {
    id: '2',
    name: 'iCare ICHD1 Hair Dryer',
    description: 'Powerful hair dryer for quick styling',
    price: 899,
    originalPrice: 1299,
    discount: 30,
    images: [
      'https://m.media-amazon.com/images/I/51fI+p5L7XL._SL1000_.jpg',
    ],
    category: 'Devices',
    subcategory: 'Appliances',
    rating: 3.8,
    reviewCount: 456,
    inStock: true,
    brand: 'iCare',
  },
  {
    id: '3',
    name: 'Richer Large 36 L Laptop Backpack',
    description: 'Spacious backpack with laptop compartment',
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    images: [
      'https://m.media-amazon.com/images/I/81+G9vV2LKL._SL1500_.jpg',
    ],
    category: 'Fashion & Beauty',
    subcategory: 'Accessories',
    rating: 4.2,
    reviewCount: 789,
    inStock: true,
    brand: 'Richer',
  },
  {
    id: '4',
    name: 'Running Shoes Pro',
    description: 'Lightweight running shoes with superior cushioning',
    price: 3499,
    originalPrice: 5999,
    discount: 42,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400',
    ],
    category: 'Sports',
    subcategory: 'Sportswear',
    rating: 4.7,
    reviewCount: 2345,
    inStock: true,
    brand: 'SportFlex',
  },
  {
    id: '5',
    name: 'Leather Wallet',
    description: 'Genuine leather wallet with multiple card slots',
    price: 799,
    originalPrice: 1299,
    discount: 38,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=400',
    ],
    category: 'Fashion & Beauty',
    subcategory: 'Accessories',
    rating: 4.2,
    reviewCount: 890,
    inStock: true,
    brand: 'LeatherCraft',
  },
  {
    id: '6',
    name: 'Yoga Mat Premium',
    description: 'Extra thick yoga mat with non-slip surface',
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    images: [
      'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400',
    ],
    category: 'Sports',
    subcategory: 'Fitness',
    rating: 4.6,
    reviewCount: 456,
    inStock: true,
    brand: 'YogaPro',
  },
];

export const mockAddresses: Address[] = [
  {
    id: '1',
    name: 'John Doe',
    phone: '+91 9876543210',
    addressLine1: '123, MG Road',
    addressLine2: 'Near Central Mall',
    city: 'Bangalore',
    state: 'Karnataka',
    pincode: '560001',
    isDefault: true,
  },
  {
    id: '2',
    name: 'John Doe',
    phone: '+91 9876543210',
    addressLine1: '456, Park Street',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400001',
    isDefault: false,
  },
];

export const mockOrders: Order[] = [
  {
    id: '1',
    orderNumber: 'ORD78654128359',
    items: [
      {
        id: '1',
        product: mockProducts[0],
        quantity: 1,
        price: mockProducts[0].price,
      },
    ],
    totalAmount: 349,
    status: 'processing',
    shippingAddress: mockAddresses[0],
    paymentMethod: 'UPI',
    createdAt: '2024-04-20T10:00:00Z',
    deliveryDate: '2024-04-27T10:00:00Z',
    trackingNumber: 'TRK78654128359',
  },
  {
    id: '2',
    orderNumber: 'ORD67843218954',
    items: [
      {
        id: '1',
        product: mockProducts[2],
        quantity: 1,
        price: mockProducts[2].price,
      },
    ],
    totalAmount: 1499,
    status: 'shipped',
    shippingAddress: mockAddresses[0],
    paymentMethod: 'Card',
    createdAt: '2024-04-18T14:30:00Z',
    deliveryDate: '2024-04-25T14:30:00Z',
    trackingNumber: 'TRK67843218954',
  },
  {
    id: '3',
    orderNumber: 'ORD92836798142',
    items: [
      {
        id: '1',
        product: mockProducts[5],
        quantity: 1,
        price: mockProducts[5].price,
      },
    ],
    totalAmount: 1299,
    status: 'delivered',
    shippingAddress: mockAddresses[0],
    paymentMethod: 'UPI',
    createdAt: '2024-04-16T10:00:00Z',
    deliveryDate: '2024-04-22T10:00:00Z',
    trackingNumber: 'TRK92836798142',
  },
  {
    id: '4',
    orderNumber: 'ORD56948731105',
    items: [
      {
        id: '1',
        product: mockProducts[3],
        quantity: 1,
        price: mockProducts[3].price,
      },
    ],
    totalAmount: 3499,
    status: 'cancelled',
    shippingAddress: mockAddresses[0],
    paymentMethod: 'Card',
    createdAt: '2024-04-12T08:20:00Z',
    deliveryDate: '2024-04-19T08:20:00Z',
    trackingNumber: 'TRK56948731105',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Order Delivered',
    message: 'Your order #ORD123456 has been delivered successfully',
    type: 'order',
    isRead: false,
    createdAt: '2024-01-05T10:00:00Z',
  },
  {
    id: '2',
    title: 'Flash Sale Alert',
    message: '50% off on electronics! Limited time offer',
    type: 'offer',
    isRead: false,
    createdAt: '2024-01-04T08:00:00Z',
  },
  {
    id: '3',
    title: 'Welcome to Zythova',
    message: 'Thank you for joining us. Happy shopping!',
    type: 'general',
    isRead: true,
    createdAt: '2024-01-01T12:00:00Z',
  },
];
